### ISSUE TITLE
Support for in-repo-addon files in `app/` (not `addon/`)?

### ISSUE THREAD

**Issue by raycohen** [ember-codemods/ember-codemods-telemetry-helpers#19]
I have a large ember app with several in-repo-addons that use the `app/components/` folder for component implementation files, rather than having the implemenetation in `addon/components/` and the re-export in `app/components`

When I run the ember-native-class-codemod against our in-repo app, I get errors like
```
 ERR lib/restaurants/app/components/second-component.js Transformation error (Cannot read property 'replace' of undefined)
TypeError: Cannot read property 'replace' of undefined
    at replace (/Users/rcohen/code/spikes/ember-lib/fake-dashboard/node_modules/ember-codemods-telemetry-helpers/lib/utils/telemetry.js:46:30)
    at _generateModuleKey (/Users/rcohen/code/spikes/ember-lib/fake-dashboard/node_modules/ember-codemods-telemetry-helpers/lib/utils/telemetry.js:39:19)
  ...
```
that appear to be because the logic in [getModulePathFor](https://github.com/ember-codemods/ember-codemods-telemetry-helpers/blob/master/lib/utils/get-module-path-for.js) only [supports](https://github.com/ember-codemods/ember-codemods-telemetry-helpers/blob/master/lib/utils/get-module-path-for.js#L96) converting files in the `addon` folder.

Would a PR be welcome that handles getting the module path for files in in-repo-addons `app` folders?

**Comment by rwjblue** [comment]
> Would a PR be welcome that handles getting the module path for files in in-repo-addons app folders?

Absolutely! It will be somewhat hard to map when there are conflicts, but I think it should be possible.

**Comment by raycohen** [comment]
The ember-native-class-codemod package doesn't pass the input/output diff test from `yarn test` when I `yarn link` this package (clean master branch) and pass `analyzeEmberObject` to `gatherTelemetryForUrl`. Is that expected?

**Comment by rwjblue** [comment]
Hmm, no I'm not sure why that would be failing :thinking:

**Comment by tylerturdenpants** [comment]
@raycohen this is fixed in #20

**Comment by rwjblue** [comment]
Reopening because I think #20 fixed the existing failures (not the issue that @raycohen was reporting).

**Comment by tylerturdenpants** [comment]
Agreed.

**Comment by tylerturdenpants** [comment]
I should have been more clear in the my previous comment.

**Comment by raycohen** [comment]
You should know better than to use `this` so lightly ;)

**Comment by rwjblue** [comment]
LOL
