### ISSUE TITLE
Support tests/ dir in addons

### ISSUE THREAD

**Issue by knownasilya** [ember-codemods/ember-codemods-telemetry-helpers#34]
AFAICT https://github.com/ember-codemods/ember-codemods-telemetry-helpers/blob/master/lib/utils/get-module-path-for.js#L93 says that it's not supported, and I get this every time:

```
 ERR tests/dummy/app/components/boolean-field/component.js Transformation error (Cannot read property 'replace' of undefined)
TypeError: Cannot read property 'replace' of undefined
    at _generateModuleKey (/Users/iradchenko/.npm/_npx/65965/lib/node_modules/ember-native-class-codemod/node_modules/ember-codemods-telemetry-helpers/lib/utils/telemetry.js:46:30)
    at getTelemetryFor (/Users/iradchenko/.npm/_npx/65965/lib/node_modules/ember-native-class-codemod/node_modules/ember-codemods-telemetry-helpers/lib/utils/telemetry.js:39:19)
    at replaceEmberObjectExpressions (/Users/iradchenko/.npm/_npx/65965/lib/node_modules/ember-native-class-codemod/transforms/helpers/parse-helper.js:177:25)
    at transformer (/Users/iradchenko/.npm/_npx/65965/lib/node_modules/ember-native-class-codemod/transforms/ember-object/index.js:26:20)
```

**Comment by rwjblue** [comment]
Seems good to add that to the conditional here.

**Comment by mansona** [comment]
This looks to be fixed with https://github.com/ember-codemods/ember-codemods-telemetry-helpers/pull/40

I don't know why it wasn't auto closed 🤔
